openapi: 3.0.0
info:
  version: 1.0.0
  title: TMDB API
  description: See https://api.themoviedb.org/3/
paths:
  /movie/popular:
    get:
      description: Returns all popular movies
      tags: ["Movies"]
      operationId: "getMoviePopular"
      parameters:
        - name: api_key
          in: query
          required: true
          description: The api key
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/MoviePopular"
        "404":
          description: Movie not found

components:
  schemas:
    MoviePopular:
      type: "object"
      "required":
        - "page"
        - "results"
      properties:
        page:
          type: "number"
        results:
          $ref: "#/components/MovieList"
    MovieList:
      type: "array"
      items:
        $ref: "#/components/Movie"
    Movie:
      type: "object"
      required:
        - "id"
        - "adult"
        - "genre_ids"
        - "original_language"
        - "original_title"
        - "overview"
        - "popularity"
        - "release_date"
        - "title"
        - "video"
        - "vote_average"
        - "vote_count"
      properties:
        adult:
          type: "boolean"
        backdrop_path:
          type: "integer"
        genre_ids":
          type: "array"
          items:
            type: "integer"
        id:
          type: "integer"
        original_language:
          type: "string"
        original_title:
          type: "string"
        overview:
          type: "string"
        popularity:
          type: "integer"
        poster_path:
          type: "string"
        release_date:
          type: "string"
        title:
          type: "string"
        video:
          type: "boolean"
        vote_average:
          type: "integer"
        vote_count:
          type: "integer"
