name: commit & pull request
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check-test-and-install-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn test
